- hosts: localhost
  vars:
    lvm_volumes:
    - vg_name: appvg
      lv_name: lv_app_build
      disk: sdc
      lv_size: 10G
      filesystem: xfs
      mount: /opt/build
  roles:
    - role: zaxos.lvm-ansible-role
