- hosts: localhost
  vars:
    lvm_volumes:
    - vg_name: appvg
      lv_name: lv_app_build
      disk: sdc
      lv_size: 10G
      filesystem: xfs
      mount: /opt/build
  roles:
    - role: zaxos.lvm-ansible-role
  tasks:
  - name: Extend tmp
    lvol:
      vg: rootvg
      lv: tmplv
      size: 10G
      resizefs: true
  - name: Extend optlv
    lvol:
      vg: rootvg
      lv: optlv
      size: 8G
      resizefs: true
      resizefs: true
  - name: Extend rootlv
    lvol:
      vg: rootvg
      lv: rootlv
      size: 10G
      resizefs: true
